name: lb-config
version: v1.20220919.1
prod:
  account:
      - "http://localhost:6000"
  payment:
      - "http://localhost:7001"
staging:
  account:
      - "http://localhost:6000"
  payment:
      - "http://localhost:7001"
dev:
  account:
      - "http://localhost:6000"
  payment:
      - "http://localhost:7001"
test:
  account:
      - "http://localhost:6000"
  payment:
      - "http://localhost:7001"