name: lb-config
version: v1.20220903.1
prod:
  - account:
      node: 1
      address: "localhost:6000"
  - payment:
      node: 1
      address: "localhost:7001"
  - blockchain:
      node: 0
staging:
  - account:
      node: 1
      address: "localhost:6000"
  - payment:
      node: 1
      address: "localhost:7001"
  - blockchain:
      node: 0
dev:
  - account:
      node: 1
      address: "localhost:6000"
  - payment:
      node: 1
      address: "localhost:7001"
  - blockchain:
      node: 0
test:
  - account:
      node: 1
      address: "localhost:6000"
  - payment:
      node: 1
      address: "localhost:7001"
  - blockchain:
      node: 0